image: node:16-alpine

before_script:
  - apk add --no-cache python3 py3-pip 

stages:
  - build
  - test
  - deploy

builder:
  stage: build
  script:
    - cd project
    - cd api_gateway && npm install && cd ..
    - cd monitor && npm install && cd ..
    - pip3 install requests pika grpcio grpcio-tools
    - cd service2 && npm install && cd ..
    - cd ..

tester:
  stage: test
  script:
    - cd project
    - cd api_gateway && npm install && cd ..
    - cd tests && npm install && npm run test && cd ..
    - cd .. 

publisher:
  stage: deploy
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  script:
    - cd project
    - docker-compose up --build
